name: Tokens
version: ${version}
main: net.thirdshift.tokens.Tokens
website: https://www.spigotmc.org/resources/tokens-multi-plugin-support-mysql-support.71941/
softdepend: [Factions, mcMMO, Vault, CombatLogX, PlaceholderAPI, ShopGUIPlus]
api-version: 1.14
authors: [TheCoolestPaul]
description: Adding another currency into Minecraft
commands:
  tokens:
    permission: tokens.use
    description: Main command for Tokens
    usage: /tokens help
  redeem:
    permission: tokens.redeem
    description: Command for redeeming Tokens
    usage: /redeem
permissions:
  tokens.use:
    default: true
    description: Required to use /tokens
  tokens.redeem:
    default: true
    description: Required to use /redeem
  tokens.redeem.mcmmo:
    default: true
    description: Required to redeem tokens for McMMO levels
  tokens.redeem.factions:
    default: true
    description: Required to redeem tokens for Faction power
  tokens.key:
    default: true
    description: Required to use keys
  tokens.redeem.sell:
    default: true
    description: Required to sell Tokens for Vault currency
  tokens.cache:
    default: false
    description: Required to edit cache settings
  tokens.buy:
    default: true
    description: Requred to use /tokens buy (token amount)
  tokens.give:
    default: true
    description: Required to use /tokens give (target player) (token amount)
  tokens.others:
    default: false
    description: Required to use /tokens (player name)
  tokens.reload:
    default: false
    description: Required to use /tokens reload
  tokens.set:
    default: false
    description: Required to use /tokens set
  tokens.add:
    default: false
    description: Required to use /tokens add
  tokens.remove:
    default: false
    description: Required to use /tokens remove